<section class="user-manager">
    <h2>User Uploads</h2>
    <table width="100%">
        <thead>
        <th width="20%">Label</th>
        <th width="40%">Filename</th>
        <th></th>
        </thead>
        <tbody>
            <?php foreach ($myUploads as $upload): ?>
                <tr>    
                    <td><?= $upload->label; ?></td>
                    <td><?= $upload->filename; ?></td>
                    <td><a href="<?= $this->url('users/upload-manager', array('action' => 'delete', 'id' => $upload->id)); ?>"> Delete</a></td>
                </tr>
            <?php endforeach; ?>
            <tr>
                <td colspan="3"><a href="<?= $this->url('users/upload-manager', array('action' => 'upload')); ?>">Add Upload</a></td>
            </tr>
        </tbody>
    </table>
</section>